v=input("digite um valor para o analisar: ")

print("tipo primitivo é:",type(v))
print("é númerico:", v.isnumeric())
print("é alfa númerico:",v.isalnum())
print("é alfa:",v.isalpha())
print("há letras maiusculas:",v.isupper())
print("há leras minusculas:",v.islower())
print("é digito:",v.isdigit())
print("é decima:",v.isdecimal())
print("é string:",v.isidentifier())
print("é imprimivel:",v.isprintable())
print("há espaço:",v.isspace())
print("está capitalizada:",v.istitle())
